import Head from 'next/head'
import * as A from './../styles/styled'

export default function Home() {
  const settings = {
    infinite: true,
    speed: 1000,
    slidesToShow: 1,
    slidesToScroll: 1,
    fade: true,
    autoplay: true,
    arrows: false,
    /* nextArrow: <SampleNextArrow />,
    prevArrow: <SamplePrevArrow />, */
  }
  return (
    <div style={{ background: '#fff7e5' }}>
      <Head>
        <title>Create Wine Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/wine-icon.png" />
      </Head>
      <A.Wrapper>
        <A.SlickSlider {...settings}>
          <A.SliderGroup>
            <img src="/images/border-collie.png" alt="보더콜리" />
            <p>Border Collie</p>
            <p>
              The Border Collie is a working and herding dog breed. They come
              from the Anglo-Scottish border region and are used to herd
              livestock, specifically sheep. The Border Collie is considered a
              highly intelligent, extremely energetic, acrobatic and athletic
              dog.
            </p>
          </A.SliderGroup>
          <A.SliderGroup>
            <img src="/images/chihuahua.png" />
            <p>Chihuahua</p>
            <p>
              The Chihuahua is one of the smallest breeds of dog, and is named
              after the Mexican state of Chihuahua.
            </p>
          </A.SliderGroup>
          <A.SliderGroup>
            <img src="/images/labrador-retriever.png" />
            <p>Labrador Retriever</p>
            <p>
              The Labrador Retriever or Labrador is a British breed of retriever
              gun dog. It was developed in the United Kingdom from fishing dogs
              imported from the colony of Newfoundland, and was named for the
              Labrador region of that colony.
            </p>
          </A.SliderGroup>
          <A.SliderGroup>
            <img src="/images/sigor-dog.png" />
            <p>Sigor Dog</p>
            <p>
              Mixed breed dogs have three or more different breeds in their
              lineage. They are sometimes called mongrels or mutts, especially
              when it's not clear what breeds make up your dog.
            </p>
          </A.SliderGroup>
        </A.SlickSlider>
        <A.GroupImg>
          <A.ImgRow>
            <img src="/images/taylor-kopel-WX4i1Jq_o0Y-unsplash.jpg" />
            <A.Overlay></A.Overlay>
            <A.ImgTitle>snack</A.ImgTitle>
            <A.Subtitle>more →</A.Subtitle>
          </A.ImgRow>
          <A.ImgRow>
            <img src="/images/alvan-nee-brFsZ7qszSY-unsplash.jpg" />
            <A.Overlay></A.Overlay>
            <A.ImgTitle>play</A.ImgTitle>
            <A.Subtitle>more →</A.Subtitle>
          </A.ImgRow>
          <A.ImgRow>
            <img src="/images/alvan-nee-1VgfQdCuX-4-unsplash.jpg" />
            <A.Overlay></A.Overlay>
            <A.ImgTitle>walk</A.ImgTitle>
            <A.Subtitle>more →</A.Subtitle>
          </A.ImgRow>
        </A.GroupImg>
      </A.Wrapper>
    </div>
  )
}
